const characters = {
	mrgz_rihefang: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["mrgzqingyu", "mrgzziyang"],
		img: "extension/阴阳师/character/mrgz_rihefang.jpeg",
	},
	mrgz_tianzhao: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["mrgzguanghui", "mrgzguangdi"],
		img: "extension/阴阳师/character/mrgz_tianzhao.jpeg",
	},
	mrgz_xuzuozhinan: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrgzshenyu", "mrgztianlei"],
		img: "extension/阴阳师/character/mr_xuzuozhinan.jpg",
	},
	mrgz_huoqubing: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrgzfenglang", "mrgzguyan"],
		img: "extension/阴阳师/character/mrgz_huoqubing.jpg",
	},
	mrgz_longyechaji: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrgzaoyi", "mrgzcanyang"],
		img: "extension/阴阳师/character/mrgz_longyechaji.jpeg",
	},
	mrgzlinghai_jinyuji: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrgzlingbo", "mrgzbaorui"],
		img: "extension/阴阳师/character/mrgzlinghai_jinyuji.jpg",
	},
	mrgzxiaolang_huangchuanzhizhu: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrgzyili"],
		img: "extension/阴阳师/character/mrxiaolang_huangchuanzhizhu.jpg",
	},
	mrgz_yuanjieshen: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrgzjieyuan"],
		img: "extension/阴阳师/character/mr_yuanjieshen.jpg",
	},
	mrgz_shenqihuang: {
		sex: "male",
		group: "yys",
		hp: 5,
		skills: ["mrgzxingliu"],
		img: "extension/阴阳师/character/mr_shenqihuang.png",
	},
	mrgz_dayuewan: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrgzfutu", "mrgzluming"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_dayuewan.jpg",
	},
	mrgz_lingluyuqian: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrgzlangqing", "mrgzzhuying"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_lingluyuqian.jpg",
	},
	mrgz_qianji: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrgzrumeng"],
		img: "extension/阴阳师/character/mr_qianji.png",
	},
	mr_xunsenxiaolunan: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrxunji", "mrsenqi"],
		img: "extension/阴阳师/character/mr_xunsenxiaolunan.png",
	},
	mrgz_chanxinyunwaijing: {
		sex: "male",
		group: "yys",
		hp: 5,
		skills: ["mrgzwanfa", "mrgzjiekong"],
		img: "extension/阴阳师/character/mr_chanxinyunwaijing.jpg",
	},
	mrgz_huojinshen: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrgzdaoyan", "mrgzzhoushi"],
		img: "extension/阴阳师/character/mr_huojinshen/mr_huojinshen.jpg",
	},
	mrgz_guiqie: {
		sex: "male",
		group: "yys",
		hp: 3,
		skills: ["mrgzguizhan", "mrgzyingshan"],
		img: "extension/阴阳师/character/mr_guiqie.jpg",
	},
	mrgz_yuanlaiguang: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrgzshence", "mrgzbuwu"],
		img: "extension/阴阳师/character/mr_yuanlaiguang.jpg",
	},
	mr_qianji: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrqianxi", "mrrumeng"],
		img: "extension/阴阳师/character/mr_qianji.png",
	},
	mrmou_huoqubing: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrqinge", "mrshoukuan", "mrzaiji"],
		img: "extension/阴阳师/character/mrmou_huoqubing.jpg",
	},
	mrmou_duoliya: {
		sex: "female",
		group: "nong",
		hp: 3,
		skills: ["mrshuiyu", "mrhuange", "mrlangyong", "mryinchang"],
		img: "extension/阴阳师/character/mrmou_duoliya.jpeg",
	},
	mrmou_shaosiyuan: {
		sex: "female",
		group: "nong",
		hp: 3,
		skills: ["mryinxing", "mrlingyuan", "mryinyuan"],
		img: "extension/阴阳师/character/mrmou_shaosiyuan/mrmou_shaosiyuan_initial.jpg",
		dieAudios: ["ext:阴阳师/audio/mrmou_shaosiyuan1.mp3", "ext:阴阳师/audio/mrmou_shaosiyuan2.mp3"],
	},
	mrmou_yuanjieshen: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mryinxing", "mryuanlai"],
		img: "extension/阴阳师/character/mrmou_yuanjieshen.jpg",
	},
	mr_tianjianrenxinguiqie: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrrenxin", "mrduane", "mryuhuo"],
		img: "extension/阴阳师/character/mr_tianjianrenxinguiqie.png",
	},
	mr_rihefang: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["mrqingyu", "mrziyang"],
		img: "extension/阴阳师/character/mr_rihefang.png",
	},
	mr_jinnaluo: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mryinxian", "mrlvqi"],
		img: "extension/阴阳师/character/mr_jinnaluo.png",
	},
	mr_zhangbeihai: {
		sex: "male",
		group: "san",
		hp: 4,
		skills: ["mrxinnian"],
		img: "extension/阴阳师/character/mr_zhangbeihai.jpeg",
	},
	mr_shaosiyuan: {
		sex: "female",
		group: "nong",
		hp: 3,
		skills: ["mrshanyuan", "mrqiyuan", "mrjieyuan", "mrtuiyou"],
		doubleGroup: ["nong", "yys"],
		img: "extension/阴阳师/character/mr_shaosiyuan/mr_shaosiyuan.jpg",
	},
	mr_shiqiang: {
		sex: "male",
		group: "san",
		hp: 4,
		skills: ["mrxiehu", "mrxingxun", "mrdongmian"],
		img: "extension/阴阳师/character/mr_shiqiang.jpg",
	},
	mr_weide: {
		sex: "male",
		group: "san",
		hp: 4,
		skills: ["mrqianjin", "mrjieti"],
		img: "extension/阴阳师/character/mr_weide.jpg",
	},
	mr_yuntianming: {
		sex: "male",
		group: "san",
		hp: 3,
		skills: ["mrfeiai", "mrzengxing", "mranle", "mranlian"],
		img: "extension/阴阳师/character/mr_yuntianming.jpg",
	},
	mr_chengxin: {
		sex: "female",
		group: "san",
		hp: 3,
		maxHp: 4,
		skills: ["mrshengmu", "mrgouhuo"],
		img: "extension/阴阳师/character/mr_chengxin.jpg",
	},
	mr_gezhe: {
		sex: "none",
		group: "san",
		hp: 3,
		skills: ["mrtanxing", "mrbaolu"],
		img: "extension/阴阳师/character/mr_gezhe.png",
	},
	mr_PDC: {
		sex: "none",
		group: "san",
		hp: 4,
		skills: ["mrjihua"],
		img: "extension/阴阳师/character/mr_PDC.jpg",
	},
	mr_luoji: {
		sex: "male",
		group: "san",
		hp: 4,
		skills: ["mrzhijian", "mrjishu", "mrcaiyi", "mrkuozhang", "mrlieren", "mrmianbi", "mrpobi"],
		clans: ["面壁者", "破壁者"],
		img: "extension/阴阳师/character/mr_luoji.jpg",
	},
	mr_xiensi: {
		sex: "male",
		group: "san",
		hp: 3,
		skills: ["mrgangyin", "mrtaowang", "mrmianbi"],
		clans: ["面壁者"],
		img: "extension/阴阳师/character/mr_xiensi.jpg",
	},
	mr_liangziyouling: {
		sex: "male",
		group: "san",
		hp: 3,
		skills: ["mrliangzi"],
		isUnseen: true,
		img: "extension/阴阳师/character/mr_liangziyouling.png",
	},
	mr_taile: {
		sex: "male",
		group: "san",
		hp: 4,
		skills: ["mrjiandui", "mrxisheng", "mrmianbi"],
		img: "extension/阴阳师/character/mr_taile.jpg",
		clans: ["面壁者"],
	},
	mr_leidiyazi: {
		sex: "male",
		group: "san",
		hp: 5,
		skills: ["mryaolan", "mrkongri", "mrmianbi"],
		img: "extension/阴阳师/character/mr_leidiyazi.jpg",
		clans: ["面壁者"],
	},
	mr_jixiaoman: {
		sex: "female",
		group: "nong",
		hp: 3,
		skills: ["mryiyi", "mryier", "mrerer", "mreryi"],
		img: "extension/阴阳师/character/mr_jixiaoman.jpg",
	},
	mr_leizhong: {
		sex: "none",
		group: "yys",
		hp: 0,
		isUnseen: true,
		img: "extension/阴阳师/character/mr_leizhong.png",
	},
	mr_xuzuozhinan: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrshenyu", "mrtianlei"],
		img: "extension/阴阳师/character/mr_xuzuozhinan.jpg",
	},
	haiguo_dayuewan: {
		sex: "male",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hgjianyu"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_dayuewan.jpg",
	},
	haiguo_lingluyuqian: {
		sex: "female",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hglangqing"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_lingluyuqian.jpg",
	},
	haiguo_jiuciliang: {
		sex: "male",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hgjinggu"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_jiuciliang.jpg",
	},
	haiguo_xieji: {
		sex: "female",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hgchuixuan"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_xieji.jpg",
	},
	haiguo_xienv: {
		sex: "female",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hgxiedu"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_xienv.jpg",
	},
	haiguo_haiming: {
		sex: "male",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hgyuanmou"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_haiming.jpg",
	},
	haiguo_fengli: {
		sex: "male",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hglongjuan"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_fengli.jpg",
	},
	haiguo_hairen: {
		sex: "female",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hgyingchu"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_hairen.jpg",
	},
	haiguo_yecha: {
		sex: "male",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hghuangquan"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_yecha.jpg",
	},
	haiguo_linghaidie: {
		sex: "female",
		group: "yys",
		hp: 0,
		isUnseen: true,
		skills: ["hglingxun"],
		img: "extension/阴阳师/character/mr_haiguo/haiguo_linghaidie.jpg",
	},
	mr_linglushanzhihun: {
		sex: "none",
		group: "yys",
		hp: 1,
		skills: ["mrjijie", "mrjuezhan"],
		img: "extension/阴阳师/character/mr_haiguo/mr_linglushanzhihun.png",
	},
	mr_yuange: {
		sex: "male",
		group: "nong",
		hp: 3,
		skills: ["mrkuilei", "mrshizhan"],
		img: "extension/阴阳师/character/mr_yuange.jpg",
		clans: ["轮椅流"],
	},
	mrlunyi_haiyue: {
		sex: "female",
		group: "nong",
		hp: 3,
		skills: ["mrshunhua", "mrhuanhai", "mrlunyi"],
		img: "extension/阴阳师/character/mrlunyi_haiyue.jpg",
		clans: ["轮椅流"],
	},
	mrlunyi_zhangfei: {
		sex: "male",
		group: "nong",
		hp: 5,
		skills: ["mrdilao", "mrlunyi"],
		img: "extension/阴阳师/character/mrlunyi_zhangfei.jpeg",
		clans: ["轮椅流"],
	},
	mrlunyi_change: {
		sex: "female",
		group: "nong",
		hp: 2,
		hujia: 1,
		skills: ["mryueying", "mryuexuan", "mryuemang", "mrlunyi"],
		img: "extension/阴阳师/character/mrlunyi_change.jpeg",
		clans: ["轮椅流"],
	},
	mrlunyi_ailin: {
		sex: "female",
		group: "nong",
		hp: 3,
		skills: ["mrxinxian", "mryuegui", "mrxuanwu", "mrlunyi"],
		img: "extension/阴阳师/character/mrlunyi_ailin.jpeg",
		clans: ["轮椅流"],
	},
	mrlunyi_kai: {
		sex: "male",
		group: "nong",
		hp: 4,
		skills: ["mrmokai", "mrlunyi"],
		img: "extension/阴阳师/character/mrlunyi_kai.jpeg",
		clans: ["轮椅流"],
	},
	mrlunyi_kuangtie: {
		sex: "male",
		group: "nong",
		hp: 4,
		skills: ["mrwuwei", "mrlunyi"],
		img: "extension/阴阳师/character/mrlunyi_kuangtie.jpeg",
		clans: ["轮椅流"],
	},
	mr_guiwangjiutuntongzi: {
		sex: "male",
		group: "yys",
		hp: 3,
		maxHp: 4,
		skills: ["mrfentian", "mrnuyan"],
		img: "extension/阴阳师/character/mr_guiwangjiutuntongzi/mr_guiwangjiutuntongzi_initial.png",
	},
	mr_bcy: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mrpuxi", "mrgugu", "mrkuaipao"],
		img: "extension/阴阳师/character/mr_bcy.jpg",
	},
	mr_yanling: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["mrmoling", "mrzhenyan"],
		img: "extension/阴阳师/character/mr_yanling.jpg",
	},
	mryaoyin_jinnaluo: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrwuyin", "mrxuanxiang"],
		img: "extension/阴阳师/character/mryaoyin_jinnaluo.jpg",
	},
	mr_yemingbianhua: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["mrchise", "mrchenmian", "mrdiaoling"],
		img: "extension/阴阳师/character/mr_yemingbianhua.png",
	},
	mr_huangkulou: {
		sex: "male",
		group: "yys",
		hp: 5,
		skills: ["mrzhanqi", "mrtiebi", "mrhuangquan"],
		img: "extension/阴阳师/character/mr_huangkulou.jpg",
	},
	mrxiaolang_huangchuanzhizhu: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrchuannu", "mrhaizhan"],
		img: "extension/阴阳师/character/mrxiaolang_huangchuanzhizhu.jpg",
	},
	mr_huangchuanzhizhu: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrjiliu", "mrtunshi"],
		img: "extension/阴阳师/character/mr_huangchuanzhizhu.jpeg",
	},
	mr_buzhihuo: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["mryehuo", "mrlishang"],
		img: "extension/阴阳师/character/mr_buzhihuo/mr_buzhihuo.jpg",
	},
	mr_shenqihuang: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrxingliu", "mrtingji", "mrmingyun"],
		img: "extension/阴阳师/character/mr_shenqihuang.png",
	},
	mr_huajiao: {
		sex: "none",
		group: "yys",
		hp: 4,
		skills: ["mrshushu", "mrtaigu"],
		img: "extension/阴阳师/character/mr_huajiao/mr_huajiao_initial.jpeg",
	},
	mrda_yuanxiaoyuan: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["mryuanjie", "mryuanshen"],
		img: "extension/阴阳师/character/mrda_yuanxiaoyuan/mrda_yuanxiaoyuan.jpg",
	},
	mrsp_yimohanse: {
		sex: "female",
		group: "yys",
		hp: 3,
		hujia: 1,
		skills: ["mryanyuan"],
		img: "extension/阴阳师/character/mrsp_yimohanse.jpg",
	},
	mr_yimohanse: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mryimo", "mrhanse"],
		img: "extension/阴阳师/character/mr_yimohanse.jpg",
	},
	mr_duoliya: {
		sex: "female",
		group: "nong",
		hp: 4,
		hujia: 1,
		skills: ["mrtianlai", "mrrenyu"],
		img: "extension/阴阳师/character/mr_duoliya/mr_duoliya.jpg",
	},
	mrfangyuan_yuanjieshen: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrfangyuan", "mrzhiyuan", "mryuanqi"],
		img: "extension/阴阳师/character/mrfangyuan_yuanjieshen.jpg",
	},
	mr_yuanjieshen: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrliangyuan", "mrshenge"],
		img: "extension/阴阳师/character/mr_yuanjieshen.jpg",
	},
	mr_yao: {
		sex: "female",
		group: "nong",
		hp: 3,
		skills: ["mrrenxing", "mrshangui"],
		img: "extension/阴阳师/character/mr_yao/mr_yao_ren.jpg",
	},
	mr_huoqubing: {
		sex: "male",
		group: "yys",
		hp: 3,
		skills: ["mrpiaoqi", "mrfenglang"],
		img: "extension/阴阳师/character/mr_huoqubing/mr_huoqubing_initial.jpg",
	},
	mr_shiyaolongyechaji: {
		sex: "female",
		group: "yys",
		hp: 3,
		skills: ["mrhuisu", "mrshixi", "mrjinzhan"],
		img: "extension/阴阳师/character/mr_shiyaolongyechaji.jpg",
	},
	mr_guiqie: {
		sex: "male",
		group: "yys",
		hp: 4,
		skills: ["mrguizhan", "mryingshan", "mrzhengfan"],
		img: "extension/阴阳师/character/mr_guiqie.jpg",
	},
	mr_ji: {
		sex: "female",
		group: "yys",
		hp: 6,
		maxHp: 7,
		skills: ["mrliuzhuan"],
		img: "extension/阴阳师/character/mr_ji/mr_ji.jpg",
	},
	mr_huojinshen: {
		sex: "female",
		group: "yys",
		hp: 3,
		hujia: 2,
		skills: ["mrdaoyan", "mrhuozhou"],
		img: "extension/阴阳师/character/mr_huojinshen/mr_huojinshen.jpg",
	},
	mr_chanxinyunwaijing: {
		sex: "male",
		group: "yys",
		hp: 8,
		skills: ["mrwanfa"],
		img: "extension/阴阳师/character/mr_chanxinyunwaijing.jpg",
	},
	mrxiaoyuan: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["白板"],
		img: "extension/阴阳师/character/mrxiaoyuan.jpg",
	},
	mr_longjue: {
		sex: "female",
		group: "yys",
		hp: 4,
		skills: ["mrxuanxue", "mrlongxi"],
		img: "extension/阴阳师/character/mr_longjue.jpg",
	},
	mr_yuanlaiguang: {
		sex: "male",
		group: "yys",
		hp: 4,
		hujia: 2,
		skills: ["mrjiazhou", "mrbuwu", "mrzhanyi"],
		img: "extension/阴阳师/character/mr_yuanlaiguang.jpg",
	},
};

export default characters;
