export default {
	"#ext:阴阳师/audio/mrdaoyan1": "我会为你祷告。",
	"#ext:阴阳师/audio/mrbuwu1": "甜心一击牛！",
	"#ext:阴阳师/audio/mryinxing1": "悲莫悲兮生别离，乐莫乐兮新相知。",
	"#ext:阴阳师/audio/mryinxing2": "判词说：知急先莫急，相逢有时机。",
	"#ext:阴阳师/audio/mrlingyuan1": "眼观六路尘缘事，线牵八方有情人。",
	"#ext:阴阳师/audio/mrlingyuan2": "曾记，曾记。聆愿而来，因缘而起。",
	"#ext:阴阳师/audio/mrlingyuan3": "一惩言无信！",
	"#ext:阴阳师/audio/mrlingyuan4": "二罚心不近！",
	"#ext:阴阳师/audio/mrlingyuan5": "一祝愿成真！",
	"#ext:阴阳师/audio/mrlingyuan6": "二佑情义深！",
	"#ext:阴阳师/audio/mrlingyuan7": "冤缘宜解。",
	"#ext:阴阳师/audio/mrlingyuan8": "不是冤家不聚头。",
	"#ext:阴阳师/audio/mrlingyuan9": "良缘易结。",
	"#ext:阴阳师/audio/mrlingyuan10": "平生难得有心人。",
	"#ext:阴阳师/audio/mrlingyuan11": "早出晚归，夙兴夜寐，庇佑情缘，舍我其谁？",
	"#ext:阴阳师/audio/mrlingyuan12": "缘者，若光阴之过客，亦岁月之归人",
	"#ext:阴阳师/audio/mryinyuan1": "因缘际会，成双成对！",
	"#ext:阴阳师/audio/mryinyuan2": "萍水相逢，呼友结朋！",
	"#ext:阴阳师/audio/mryinyuan3": "习惯就好，司缘堂向来业绩第一（小红：习惯啦！）",
	"#ext:阴阳师/audio/mrmou_shaosiyuan1:die": "故人兮永离，相逢兮无期；梦回兮年少，梦醒兮杳杳……",
	"#ext:阴阳师/audio/mrmou_shaosiyuan2:die": "“天生孤星，灾祸横行”——这便是我曾被预言的命运",
};
